name: Call Webhook on Push

on:
  push:
    branches:
      - main

jobs:
  call-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Call Webhook
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }}
